### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by BrycensRanch** [juancarlospaco/antispam-action#48]
**Moderated for suspected Spam.**
    - Only English language is supported for issues, because moderators only speak English.
    <details>
    <summary>Diagnostics</summary>
    **Title**
    <code>[["polish",0.3308333333333333],["latin",0.3208333333333333],["vietnamese",0.21999999999999997],["indonesian",0.21833333333333338],["german",0.21499999999999997]]</code>
    **Body**
    <code>[["english",0.27281481481481473],["pidgin",0.18781481481481477],["latin",0.1731851851851851],["french",0.1595185185185185],["italian",0.15581481481481485]]</code>
    </details>

**Comment by juancarlospaco** [comment]
![antispam-action-works-2024-12-29_11-22](https://github.com/user-attachments/assets/d9566b9b-8ffa-4de1-8323-4ee37f0ed111)

🙂👍
